INSERT INTO destinations (
  name, 
  description, 
  image_url, 
  country, 
  price_from, 
  duration, 
  group_size, 
  availability_status, 
  departure_start_date, 
  departure_end_date, 
  gallery_images, 
  hotels, 
  inclusions, 
  exclusions, 
  payment_options, 
  first_day_info, 
  last_day_info, 
  itinerary,
  display_order
) VALUES (
  'China: O melhor dos 2 mundos',
  'Da Grande Muralha à Cidade Proibida, dos Guerreiros de Terracota à moderna Shanghai. Uma viagem épica pela história milenar e o futuro vibrante da China, com um toque especial das montanhas encantadoras do interior.',
  'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/6988295eab60382ac956dcb6/bd3162b6c_VIAJECOMAGENTE-2.png',
  'China',
  'USD 3.400',
  '13 dias',
  '6-12 pessoas',
  'available',
  '2026-08-22',
  '2026-09-04',
  '["https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/6988295eab60382ac956dcb6/bd3162b6c_VIAJECOMAGENTE-2.png", "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&q=80"]'::jsonb,
  '[{"name": "Jinglai Hotel Selected", "rating": 4}, {"name": "The Hidden House (Chengdu)", "rating": 4}]'::jsonb,
  '["Entrada em todas as atrações", "Guias locais credenciados nos principais pontos", "Acomodação em quarto duplo com café da manhã", "Transporte interno incluindo trens e voos", "Acompanhamento Pré-Embarque"]'::jsonb,
  '["Passagens internacionais", "Gastos Pessoais", "Seguro Viagem", "Alimentação"]'::jsonb,
  '["PIX", "Boleto Parcelado Sem Juros", "Cartão de Crédito (4,7% de taxas se aplicam)"]'::jsonb,
  '{"title":"Chegada","description":"Buscaremos você no aeroporto e faremos o check-in no hotel.","activities":["Buscaremos você no aeroporto", "Check in no hotel e boas vindas"]}'::jsonb,
  '{"title":"Retorno","description":"Visita ao Exército de Terracota e retorno para Pequim para embarque.","activities":["Exército de Terracota", "Retorno para Pequim"]}'::jsonb,
  '[
    {"day":"1","title":"Chegada","description":"Buscaremos você no aeroporto. Check in no hotel e boas vindas.","activities":["Buscaremos você no aeroporto", "Check in no hotel e boas vindas"]},
    {"day":"2","title":"Pequim","description":"Visita à Cidade Proibida, Templo do Céu e passeio pelos Hutongs.","activities":["Cidade Proibida", "Templo do Céu", "Hutongs"]},
    {"day":"3","title":"Pequim - Muralha","description":"Visita à Muralha da China com descida de tobogã. Ida para Shanghai.","activities":["Muralha da China com descida de tobogã", "Ida para Shanghai"]},
    {"day":"4","title":"Shanghai","description":"Exploração da Concessão Francesa, Old Town, Skyline e passeio pelo The Bund e Pudong.","activities":["Concessão Francesa", "Old Town", "Skyline", "Passeio pelo The Bund e Pudong"]},
    {"day":"5","title":"Ida para Yangshuo","description":"Voo para Guilin com transfer. Passeio pela cidade de Yangshuo e sua vida noturna.","activities":["Voo para Guilin com transfer", "Passeio pela cidade de Yangshuo e sua vida noturna"]},
    {"day":"6","title":"Yangshuo","description":"Tour pelo Rio Li e passeio pelas Montanhas de Yangshuo.","activities":["Tour pelo Rio Li", "Passeio pelas Montanhas de Yangshuo"]},
    {"day":"7","title":"Ida para Zhangjiajie","description":"Viagem para Zhangjiajie e visita à Cidade Cênica no centro da cidade.","activities":["Ida para Zhangjiajie", "Cidade Cênica no centro da cidade"]},
    {"day":"8","title":"Zhangjiajie - Portal do Céu","description":"Visita à Montanha Tianmen, incluindo o Portal do Céu e a Estrada de vidro de 99 curvas.","activities":["Montanha Tianmen (Portal do Céu, Estrada de vidro de 99 curvas)"]},
    {"day":"9","title":"Zhangjiajie - Montanhas do Avatar","description":"Parque das Montanhas do Avatar. Tarde e noite em Furong Town (cidade da cachoeira).","activities":["Parque das Montanhas do Avatar", "Tarde e noite em Furong Town (cidade da cachoeira)"]},
    {"day":"10","title":"Ida para Chengdu","description":"Viagem para Chengdu, visita à Pedestrian Street, Fontes de Bambu e ruas iluminadas.","activities":["Ida para Chengdu", "Pedestrian Street", "Fontes de Bambu", "Rua do centro iluminadas"]},
    {"day":"11","title":"Chengdu - Pandas","description":"Visita ao Centro dos Pandas, Parque do Povo com chá tradicional e visita à ponte iluminada.","activities":["Centro dos Pandas", "Parque do Povo com opção de tomar o chá tradicional", "Visita a ponte iluminada"]},
    {"day":"12","title":"Ida para Xi''an","description":"Viagem para Xi''an, passeio pelo bairro muçulmano, old town e cidade murada.","activities":["Ida para Xi''an", "Passeio pelo bairro muçulmano", "Passeio pelo old town e cidade murada"]},
    {"day":"13","title":"Xi''an - Guerreiros de Terracota","description":"Visita ao Exército de Terracota e retorno para Pequim.","activities":["Exército de Terracota", "Retorno para Pequim"]}
  ]'::jsonb,
  3
);
