-- Seed data for countries table
INSERT INTO countries (name, code, description, featured) VALUES
('Brasil', 'BR', 'País do futebol, carnaval e praias paradisíacas. Destinos imperdíveis como Rio de Janeiro, São Paulo e o Nordeste.', true),
('Estados Unidos', 'US', 'Terra das oportunidades e paisagens diversificadas. De Nova York à Califórnia, passando pela Flórida.', true),
('França', 'FR', 'País da torre Eiffel, vinhos e gastronomia refinada. Paris, a cidade do amor, e a Riviera Francesa.', true),
('Itália', 'IT', 'Berço do Império Romano, Renascimento e da melhor culinária do mundo. Roma, Veneza e Florença.', true),
('Espanha', 'ES', 'País da paella, flamenco e praias mediterrâneas. Madrid, Barcelona e as ilhas Baleares.', true),
('Portugal', 'PT', 'País dos descobrimentos, vinho do Porto e Lisboa charmosa. Do Algarve ao Douro.', true),
('Argentina', 'AR', 'Tango, carne e patagônia. Buenos Aires, Bariloche e as Cataratas do Iguaçu.', false),
('Chile', 'CL', 'País longo e estreito com desertos, geleiras e vinhos. Atacama, Patagônia e Ilha de Páscoa.', false),
('México', 'MX', 'Civilizações antigas, praias caribenhas e gastronomia única. Cidade do México, Cancún e Guadalajara.', false),
('Canadá', 'CA', 'Natureza exuberante, cidades amigáveis e quatro estações bem definidas. Toronto, Vancouver e Quebec.', false),
('Austrália', 'AU', 'País dos cangurus, Great Barrier Reef e cidades vibrantes. Sydney, Melbourne e a Gold Coast.', false),
('Japão', 'JP', 'Tradição milenar encontrada com tecnologia de ponta. Tóquio, Quioto e o Monte Fuji.', false),
('China', 'CN', 'Grande muralha, cidades imperiais e modernidade impressionante. Pequim, Xangai e a Rota da Seda.', false),
('Índia', 'IN', 'Taj Mahal, templos milenares e cultura vibrante. Nova Delhi, Agra e as praias de Goa.', false),
('Tailândia', 'TH', 'Templos dourados, praias paradisíacas e gastronomia exótica. Bangcoc, Phuket e Chiang Mai.', false),
('Indonésia', 'ID', 'Mil ilhas, templos antigos e florestas tropicais. Bali, Jacarta e Komodo.', false),
('Vietnã', 'VN', 'Baía de Ha Long, história rica e paisagens deslumbrantes. Hanói, Ho Chi Minh e a Costa Central.', false),
('África do Sul', 'ZA', 'Safaris, montanhas e cidades vibrantes. Cidade do Cabo, Joanesburgo e Kruger.', false),
('Egito', 'EG', 'Pirâmides, faraós e o rio Nilo. Cairo, Luxor e o Vale dos Reis.', false),
('Grécia', 'GR', 'Berço da democracia, filosofia e mitologia. Atenas, Santorini e as ilhas gregas.', false),
('Turquia', 'TR', 'Ponte entre Oriente e Ocidente. Istambul, Capadócia e as praias do Mediterrâneo.', false),
('Reino Unido', 'GB', 'Monarquia, história e modernidade. Londres, Edimburgo e a paisagem escocesa.', false),
('Alemanha', 'DE', 'Precisão engenharia, cerveja e história. Berlim, Munique e a Floresta Negra.', false),
('Holanda', 'NL', 'Canais, moinhos de vento e liberdade. Amsterdã, Keukenhof e os campos de tulipas.', false),
('Suíça', 'CH', 'Alpes, chocolate e neutralidade. Zurique, Genebra e Interlaken.', false),
('Suécia', 'SE', 'Design minimalista, natureza e qualidade de vida. Estocolmo, Gotemburgo e a aurora boreal.', false),
('Noruega', 'NO', 'Fiordes dramáticos, aurora boreal e vikingues. Oslo, Bergen e o Cabo Norte.', false),
('Dinamarca', 'DK', 'Felicidade, design e contos de fadas. Copenhague, Legoland e a Pequena Sereia.', false),
('Finlândia', 'FI', 'Saunas, aurora boreal e mil lagos. Helsinque, Rovaniemi e Lapônia.', false),
('Rússia', 'RU', 'Vastidão, história imperial e arte. Moscou, São Petersburgo e o Transiberiano.', false),
('Coreia do Sul', 'KR', 'K-pop, tecnologia e tradição. Seul, Busan e a ilha de Jeju.', false),
('Singapura', 'SG', 'Cidade-estado moderna, jardins botânicos e gastronomia fusion.', false),
('Maldivas', 'MV', 'Paraísos tropicais, águas cristalinas e resorts sobre a água. Malé e atóis de luxo.', false),
('Dubai', 'AE', 'Modernidade extrema, luxo e desertos. Burj Khalifa, shoppings e palmeiras artificiais.', false),
('Israel', 'IL', 'Terra santa, história milenar e inovação. Jerusalém, Tel Aviv e o Mar Morto.', false),
('Marrocos', 'MA', 'Mercados exóticos, desertos do Saara e arquitetura islâmica. Marrakesh, Fez e Casablanca.', false);