INSERT INTO destinations (
  name, 
  description, 
  image_url, 
  country, 
  price_from, 
  duration, 
  group_size, 
  availability_status, 
  departure_start_date, 
  departure_end_date, 
  gallery_images, 
  hotels, 
  inclusions, 
  exclusions, 
  payment_options, 
  first_day_info, 
  last_day_info, 
  itinerary
) VALUES (
  'Tailândia Festival das Lanternas',
  'Viagens pela Ásia com grupos pequenos de brasileiros.',
  'https://phiphibrazuca.com/wp-content/uploads/2021/07/Festival_Lanternas_Chiang_Mai_Tailandia_Fogos.jpg',
  'Tailândia',
  'USD 3.300',
  '15 dias',
  '6-12 pessoas',
  'available',
  '2026-11-21',
  '2026-12-04',
  '["https://cf.bstatic.com/xdata/images/hotel/max1024x768/563175365.jpg","https://cf.bstatic.com/xdata/images/hotel/max1024x768/613789630.jpg","https://cf.bstatic.com/xdata/images/hotel/max1024x768/281257565.jpg","https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/66589630.jpg"]'::jsonb,
  '["Huen Hug Hotel","Seekers Finders Rama IV Hotel","Phi Phi Anita Resort","Vacation Village"]'::jsonb,
  '["Passeios e atrações do roteiro","Passagens e transportes internos","Acomodação em quartos duplos","Long Boat Tour","Visita ao santuário","Ingressos do Festival das Lanternas","Acompanhamento Pré-embarque","Líderes brasileiros"]'::jsonb,
  '["Passagens internacionais","Gastos pessoais","Alimentação","Seguro viagem"]'::jsonb,
  '["PIX","Boleto","Cartão de Crédito"]'::jsonb,
  '{"title":"A chegada","description":"Chegada em Bangkok, busca no aeroporto e check-in no hotel.","activities":["Recepcção no aeroporto","Transfer privativo","Check-in no hotel em Bangkok"]}'::jsonb,
  '{"title":"Despedida","description":"Fim da nossa viagem com novas memórias incríveis!","activities":["Check-out do hotel","Transfer para o aeroporto","Retorno ao Brasil"]}'::jsonb,
  '[{"day":"2","title":"Início da aventura","description":"Ida para Chiang Mai, City Tour e curtir a noite em Old Town.","activities":["Voo/Transporte para Chiang Mai","City Tour guiado","Exploração noturna em Old Town"]},{"day":"3","title":"Festival das Lanternas","description":"Tempo livre pela manhã, Festival das lanternas durante a tarde e noite, ver monges pela manhã nos rituais dos templos.","activities":["Observação de rituais matinais","Tempo livre","Participação no Festival das Lanternas (Loy Krathong/Yi Peng)"]},{"day":"4","title":"Chiang Rai","description":"Visita aos templos icônicos: Templo Branco, Templo Preto e Templo Azul.","activities":["Tour de dia inteiro em Chiang Rai","Visita ao Wat Rong Khun (Branco)","Baandam Museum (Preto)","Wat Rong Suea Ten (Azul)"]},{"day":"5","title":"Chiang Mai e Elefantes","description":"Manhã no santuário dos elefantes, visita ao Art Village à tarde e Mercado noturno.","activities":["Interação ética com elefantes","Visita à vila de artistas","Compras no Night Bazaar"]},{"day":"6","title":"Partida para o litoral","description":"Ida para Krabi e curtir a praia à tarde.","activities":["Voo/Transporte para Krabi","Check-in","Tempo livre na praia"]},{"day":"7","title":"Krabi Islands","description":"Passeio de barco pelas ilhas, Mercado noturno e visita ao centro de Krabi.","activities":["Island hopping tour","Visita ao Krabi Town","Jantar no mercado noturno local"]},{"day":"8","title":"Hong Island","description":"Passeio de Barco para Hong Island.","activities":["Tour de barco para a paradisíaca Hong Island","Snorkeling","Relaxamento"]},{"day":"9","title":"Phi Phi Island","description":"Ferry Boat para PhiPhi, Noite para ver festa na praia Loh Dalum Bay.","activities":["Ferry para as Ilhas Phi Phi","Check-in","Nightlife em Loh Dalum Bay"]},{"day":"10","title":"Phi Phi Classics","description":"Visita à Maya Bay, opção de mergulho extra e Bar Muai Thai.","activities":["Passeio para Maya Bay","Mergulho opcional","Assistir lutas de Muay Thai em bares locais"]},{"day":"11","title":"Retorno à Capital","description":"Retorno para Bangkok, visita à Khaosan Road e massagem nos pés.","activities":["Voo de retorno a Bangkok","Visita à icônica Khaosan Road","Experiência de massagem tailandesa"]},{"day":"12","title":"Mercados Tradicionais","description":"Visita ao Mercado Flutuante e Mercado do Trem.","activities":["Tour Damnoen Saduak (Flutuante)","Tour Maeklong Railway Market (Mercado do Trem)"]},{"day":"13","title":"Bangkok Cultural","description":"Templo Wat Pho, Templo Wat Phra Kaew e China Town à tarde com food tour.","activities":["Visita ao Grande Palácio","Buda Reclinado","Exploração gastronômica em China Town"]}]'::jsonb
);
