INSERT INTO destinations (
  name, 
  description, 
  image_url, 
  country, 
  price_from, 
  duration, 
  group_size, 
  availability_status, 
  departure_start_date, 
  departure_end_date, 
  gallery_images, 
  hotels, 
  inclusions, 
  exclusions, 
  payment_options, 
  first_day_info, 
  last_day_info, 
  itinerary
) VALUES (
  'Taj Mahal & Rajastão',
  'Uma jornada épica pelo coração da Índia, passando por Delhi, Agra e as cidades coloridas do Rajastão. Visite o icônico Taj Mahal ao nascer do sol, explore palácios de marajás em Jaipur e perca-se nas ruas de Jodhpur, a cidade azul.',
  'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/6988295eab60382ac956dcb6/bd3162b6c_VIAJECOMAGENTE-2.png',
  'India',
  'USD 12.900',
  '14 dias',
  '6-10 pessoas',
  'sold_out',
  '2026-03-02',
  '2026-03-14',
  '["https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/6988295eab60382ac956dcb6/bd3162b6c_VIAJECOMAGENTE-2.png", "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&q=80"]'::jsonb,
  '[{"name": "Hotéis 4 estrelas (Nomes específicos não listados)", "rating": 4, "location": "Delhi, Agra, Jaipur", "image": "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&q=80"}]'::jsonb,
  '["Acomodação em hotéis 4 estrelas com café da manhã", "Todos os transfers e transportes em veículo climatizado", "Guia em português durante toda a viagem", "Ingressos para todos os monumentos do roteiro", "Passeio de elefante no Forte de Amber", "Seguro viagem internacional", "Todas as taxas e impostos", "Jantar de boas-vindas"]'::jsonb,
  '["Passagens aéreas Brasil - Índia - Brasil", "Visto de entrada na Índia", "Refeições não mencionadas (almoço e jantar)", "Bebidas alcoólicas", "Despesas pessoais", "Gorjetas para guias e motoristas"]'::jsonb,
  '["PIX", "Boleto Parcelado Sem Juros", "Cartão de Crédito (4,7% de taxas se aplicam)", "Pagamento fragmentado (30% de entrada + valor final 30 dias antes do embarque)"]'::jsonb,
  '{"title":"A chegada","description":"Recepção no aeroporto e traslado ao hotel. À tarde, tour pelos principais pontos de Delhi.","activities":["Transfer aeroporto","Check-in no hotel","City tour Delhi","Jantar de boas-vindas"]}'::jsonb,
  '{"title":"Despedida","description":"Fim da nossa viagem com novas memórias incríveis do Taj Mahal.","activities":["Check-out do hotel","Transfer para o aeroporto","Retorno ao Brasil"]}'::jsonb,
  '[{"day":"1","title":"Chegada em Delhi","description":"Recepção no aeroporto e traslado ao hotel. À tarde, tour pelos principais pontos de Delhi, incluindo o Portão da Índia e o Templo de Lótus.","activities":["Transfer aeroporto","Check-in no hotel","City tour Delhi","Jantar de boas-vindas"]},{"day":"2","title":"Delhi - Old Delhi","description":"Explore a Delhi antiga com visita ao Forte Vermelho, Jama Masjid e um passeio de riquixá pelas ruas estreitas de Chandni Chowk.","activities":["Forte Vermelho","Mesquita Jama Masjid","Passeio de riquixá","Mercado de especiarias"]},{"day":"3","title":"Delhi - Agra","description":"Viagem para Agra. Visita ao Forte de Agra, patrimônio mundial da UNESCO, com vista para o Taj Mahal ao pôr do sol.","activities":["Transfer para Agra","Forte de Agra","Vista do Taj ao pôr do sol"]},{"day":"4","title":"Taj Mahal ao Amanhecer","description":"Experiência mágica de ver o Taj Mahal ao nascer do sol. Tarde livre para explorar os mercados de Agra.","activities":["Taj Mahal ao nascer do sol","Tarde livre","Compras em mercados locais"]},{"day":"5","title":"Agra - Jaipur","description":"Viagem para Jaipur com parada em Fatehpur Sikri, cidade fantasma mogol. Chegada em Jaipur à tarde.","activities":["Fatehpur Sikri","Transfer para Jaipur","Passeio pela cidade rosa"]}]'::jsonb
);
