INSERT INTO destinations (
  name, 
  description, 
  image_url, 
  country, 
  price_from, 
  duration, 
  group_size, 
  availability_status, 
  departure_start_date, 
  departure_end_date, 
  gallery_images, 
  hotels, 
  inclusions, 
  exclusions, 
  payment_options, 
  first_day_info, 
  last_day_info, 
  itinerary,
  display_order
) VALUES (
  'Além de Bali',
  'Das praias paradisíacas de Bali aos dragões de Komodo, esta viagem combina espiritualidade, natureza exuberante e aventura. Arrozais em terraços, templos milenares e talvez, o pôr do sol mais bonito do mundo.',
  'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/6988295eab60382ac956dcb6/bd3162b6c_VIAJECOMAGENTE-2.png',
  'Indonésia',
  'USD 2.880',
  '12 dias',
  '6-12 pessoas',
  'available',
  '2026-07-05',
  '2026-07-17',
  '["https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/6988295eab60382ac956dcb6/bd3162b6c_VIAJECOMAGENTE-2.png", "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80", "https://phinisitrip.com/wp-content/uploads/2025/09/Sora-Liveaboard-Signature-Cabin-3-1.webp", "https://pix8.agoda.net/hotelImages/41186578/0/18c445e4b4dba9cfc6d65c21ae2add9a.jpg?ce=2&s=1024x"]'::jsonb,
  '[{"name": "Zasgo Hotel", "rating": 4, "location": "Ubud"}, {"name": "Swiss-Belresort Pecatu", "rating": 4, "location": "Uluwatu"}, {"name": "Kubu Rama Cottage", "rating": 4, "location": "Ubud"}]'::jsonb,
  '["Acomodação em quartos duplos em hotéis 4 estrelas", "Locomoção Interna - incluindo aéreo", "Entrada em atrações e monumentos", "Navegação com pensão completa no barco", "Transfers de aeroporto", "Acompanhamento Pré Embarque"]'::jsonb,
  '["Passagem internacional", "Taxa de entrada no parque de Komodo (R$180)", "Gastos Pessoais", "Alimentação (exceto as descritas no roteiro)"]'::jsonb,
  '["PIX", "Boleto Parcelado Sem Juros", "Cartão de Crédito (4,7% de taxas se aplicam)", "Pagamento fragmentado (30% de entrada + valor final 30 dias antes do embarque)"]'::jsonb,
  '{"title":"BALI - UBUD","description":"Chegada em Bali, transfer para o Hotel de UBUD e boas vindas.","activities":["Chegada em Bali", "Transfer para o Hotel", "Boas vindas"]}'::jsonb,
  '{"title":"BALI - ULUWATU","description":"Dia livre para aproveitar como preferir (praia, beach clubs, feirinhas de artesanato).","activities":["Dia livre", "Check-out", "Transfer aeroporto"]}'::jsonb,
  '[
    {"day":"1","title":"Chegada em Ubud","description":"Chegada em Bali, transfer para o Hotel de UBUD e boas vindas.","activities":["Chegada em Bali", "Transfer para o Hotel", "Boas vindas"]},
    {"day":"2","title":"Espiritualidade e Natureza","description":"Ritual Melukat na Cachoeira e visita aos icônicos arrozais em terraços de Bali.","activities":["Ritual Melukat", "Cachoeira", "Visita aos Arrozais"]},
    {"day":"3","title":"Cultura e Bem-estar","description":"Aula de Yoga, oficina de jóia de prata com artesãos locais e tempo livre pelo centro de Ubud.","activities":["Aula de Yoga", "Cachoeira", "Oficina de jóia de prata", "Tempo livre"]},
    {"day":"4","title":"Templos e Cura","description":"Visita aos templos sagrados pela manhã e Sound Healing (cura pelo som) à tarde.","activities":["Visita aos Templos", "Sound healing"]},
    {"day":"5","title":"Rumo a Flores","description":"Voo para a Ilha de Flores (Labuan Bajo). Tempo livre para curtir a praia e a cidade.","activities":["Voo para Flores", "Tempo livre em Labuan Bajo"]},
    {"day":"6","title":"Início da Navegação","description":"Embarque em liveaboard. Almoço no barco, Ilha Kelor, snorkel em Manjarite e pôr do sol em Kalong Island.","activities":["Almoço no Barco", "Ilha Kelor", "Snorkel em Manjarite", "Pôr do sol em Kalong Island"]},
    {"day":"7","title":"Parque Nacional de Komodo","description":"Visita a Padar Island, Manta Point, encontro com os Dragões de Komodo e relaxamento em Taka Makassar.","activities":["Padar Island", "Manta Point", "Parque Nacional de Komodo", "Taka Makassar"]},
    {"day":"8","title":"Final da Navegação","description":"Exploração das Ilhas Sebayur e Kanawa antes do retorno para Labuan Bajo.","activities":["Ilhas Sebayur", "Ilha Kanawa", "Retorno para Labuan Bajo"]},
    {"day":"9","title":"Retorno a Bali - Uluwatu","description":"Voo de volta para Bali. Cerimônia no Templo do Penhasco com danças tradicionais.","activities":["Voo para Bali", "Cerimônia Templo do Penhasco", "Danças locais"]},
    {"day":"10","title":"Praias de Uluwatu","description":"Manhã na famosa Praia de Padang Padang e pôr do sol épico na colina.","activities":["Praia de Padang Padang", "Pôr do sol na colina"]},
    {"day":"11","title":"Nusa Penida","description":"Day trip para Nusa Penida visitando Kelingking Beach e Diamond Beach.","activities":["Partida cedo", "Kelingking Beach", "Diamond Beach"]},
    {"day":"12","title":"Dia Livre em Uluwatu","description":"Dia livre para aproveitar como preferir: praia, beach clubs ou feirinhas de artesanato.","activities":["Dia livre", "Praia", "Beach clubs", "Feirinhas"]}
  ]'::jsonb,
  4
);
