INSERT INTO destinations (
  name, 
  description, 
  image_url, 
  country, 
  price_from, 
  duration, 
  group_size, 
  availability_status, 
  departure_start_date, 
  departure_end_date, 
  gallery_images, 
  hotels, 
  inclusions, 
  exclusions, 
  payment_options, 
  first_day_info, 
  last_day_info, 
  itinerary,
  highlights,
  display_order
) VALUES (
  'Tailândia Festival das Lanternas',
  'Bangkok, templos dourados, mercados flutuantes e as praias paradisíacas do sul. A Tailândia perfeita para quem visita pela primeira vez, com o equilíbrio ideal entre cultura, natureza, vida noturna e relaxamento.',
  'https://phiphibrazuca.com/wp-content/uploads/2021/07/Festival_Lanternas_Chiang_Mai_Tailandia_Fogos.jpg',
  'Tailândia',
  'USD 3.300',
  '14 dias',
  '6-12 pessoas',
  'available',
  '2026-11-22',
  '2026-12-05',
  '["https://phiphibrazuca.com/wp-content/uploads/2021/07/Festival_Lanternas_Chiang_Mai_Tailandia_Fogos.jpg", "https://cf.bstatic.com/xdata/images/hotel/max1024x768/563175365.jpg?k=cf83337b1faef0e4896b59b84f7d593b3f285b39cd5e63b2c3d91bca0f0c67da&o=", "https://cf.bstatic.com/xdata/images/hotel/max1024x768/613789630.jpg?k=6298efef7774b6433c6ee36906ecfbcb41cab3e78aecc6d6d2b49187dce49839&o=", "https://cf.bstatic.com/xdata/images/hotel/max1024x768/281257565.jpg?k=8dc0b7322bcb7c6bb68af2834ae629949131c5768678deec32bfeea10229e5eb&o="]'::jsonb,
  '[{"name": "Seekers Finders Rama IV Hotel", "rating": 4, "location": "Bangkok"}, {"name": "Huen Hug Hotel", "rating": 3, "location": "Chiang Mai"}, {"name": "Phi Phi Anita Resort", "rating": 3, "location": "Phi Phi"}]'::jsonb,
  '["Passeios e atrações do roteiro", "Passagens e transportes para locomoção interna", "Acomodação em quartos duplos com café da manhã", "Long Boat Tour pelas Ilhas", "Visita ao santuário dos elefantes", "Ingressos para o Festival das Lanternas", "Acompanhamento Pré-embarque", "Líderes brasileiros acompanhando"]'::jsonb,
  '["Passagens internacionais", "Gastos pessoais e com documentação", "Alimentação", "Seguro viagem"]'::jsonb,
  '["Pix", "Boleto", "Cartão de Crédito"]'::jsonb,
  '{"title":"Chegada em Bangkok","description":"Busca no aeroporto e check-in no hotel. Início da aventura.","activities":["Chegada em Bangkok", "Transfer aeroporto", "Check-in"]}'::jsonb,
  '{"title":"Fim da viagem","description":"Encerramento da viagem com novas memórias incríveis e retorno.","activities":["Check-out", "Transfer aeroporto", "Retorno"]}'::jsonb,
  '[
    {"day":"1","title":"A chegada","description":"Chegada em Bangkok, busca no aeroporto e check-in no hotel.","activities":["Chegada em Bangkok", "Check-in"]},
    {"day":"2","title":"Bangkok Imperial","description":"Visita ao Templo do Buda Reclinado, Grand Palace e Mercado de Flores.","activities":["Templo do Buda Reclinado", "Grand Palace", "Mercado de flores"]},
    {"day":"3","title":"Festival das Lanternas em Chiang Mai","description":"Voo para Chiang Mai. Rituais dos templos pela manhã e o mágico Festival das Lanternas à noite.","activities":["Ritos matinais", "Festival das lanternas"]},
    {"day":"4","title":"Triângulo Dourado - Chiang Rai","description":"Bate-volta para Chiang Rai visitando os Templos Branco, Preto e Azul.","activities":["Templo Branco", "Templo Preto", "Templo Azul"]},
    {"day":"5","title":"Elefantes e Cultura","description":"Manhã no santuário de elefantes ético e visita ao Art Village à tarde.","activities":["Santuário dos elefantes", "Art Village", "Mercado noturno"]},
    {"day":"6","title":"Rumo às Praias - Krabi","description":"Voo para Krabi. Tarde livre para curtir a praia.","activities":["Voo para Krabi", "Praia à tarde"]},
    {"day":"7","title":"Ilhas de Krabi","description":"Passeio de barco pelas ilhas vizinhas e visita ao vibrante mercado noturno.","activities":["Passeio de barco", "Centro de Krabi", "Mercado noturno"]},
    {"day":"8","title":"Hong Island","description":"Dia dedicado às águas cristalinas de Hong Island em um passeio exclusivo.","activities":["Passeio Hong Island"]},
    {"day":"9","title":"Paraíso Phi Phi","description":"Ferry para as Ilhas Phi Phi. Noite de festa (opcional) em Loh Dalum Bay.","activities":["Ferry para PhiPhi", "Loh Dalum Bay"]},
    {"day":"10","title":"Maya Bay e Além","description":"Visita à famosa Maya Bay e Pileh Lagoon. Opção de mergulho disponível.","activities":["Maya Bay", "Pileh Lagoon", "Bar Muai Thai"]},
    {"day":"11","title":"Retorno a Bangkok","description":"Voo de volta. Noite na Khaosan Road e massagem tradicional tailandesa.","activities":["Voo para Bangkok", "Khaosan Road", "Massagem nos pés"]},
    {"day":"12","title":"Mercados Típicos","description":"Dia de explorar o Mercado Flutuante e o curioso Mercado do Trem.","activities":["Mercado flutuante", "Mercado do Trem"]},
    {"day":"13","title":"China Town e Gastronomia","description":"Templos históricos e tour gastronômico por China Town.","activities":["Wat Pho", "Wat Phra Kaew", "Food tour China Town"]},
    {"day":"14","title":"Despedida","description":"Encerramento da viagem e transfer para o aeroporto.","activities":["Encerramento", "Transfer aeroporto"]}
  ]'::jsonb,
  '[
    {"title": "Festival das Lanternas", "image_url": "https://phiphibrazuca.com/wp-content/uploads/2021/07/Festival_Lanternas_Chiang_Mai_Tailandia_Fogos.jpg"},
    {"title": "Santuário de Elefantes", "image_url": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/563175365.jpg?k=cf83337b1faef0e4896b59b84f7d593b3f285b39cd5e63b2c3d91bca0f0c67da&o="},
    {"title": "Ilhas Phi Phi", "image_url": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/613789630.jpg?k=6298efef7774b6433c6ee36906ecfbcb41cab3e78aecc6d6d2b49187dce49839&o="},
    {"title": "Mercado Flutuante", "image_url": "https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/66589630.jpg?k=ed5878bfeedaecf956f1ad06b84ecd2d0f3a34b3401bf537597305da8e8951dc&o=&s=1024x"}
  ]'::jsonb,
  5
);
